add warning and print number spellcheck warnings

diff --git a/.github/workflows/build-ss3-manual-pdf.yml b/.github/workflows/build-ss3-manual-pdf.yml
--- a/.github/workflows/build-ss3-manual-pdf.yml
+++ b/.github/workflows/build-ss3-manual-pdf.yml
@@ -41,9 +41,12 @@ jobs:
           root_file: SS330_User_Manual.tex
           args: --check en --dict dictionary.txt --ignore sh:nobreak,sh:stacked,sh:nsubdiv,sh:seclen,sh:nonp,sh:hctab,sh:figref,lt:en:UNIT_SPACE,lt:en:UPPERCASE_SENTENCE_START,lt:en:COMMA_COMPOUND_SENTENCE_2,lt:en:COMMA_COMPOUND_SENTENCE,lt:en:ENGLISH_WORD_REPEAT_BEGINNING_RULE,lt:en:ENGLISH_WORD_REPEAT_RULE,lt:en:ENTER_IN,lt:en:CD_NN,lt:en:PHRASE_REPETITION,lt:en:SETUP_VERB,lt:en:ONES
 
-      # - name: Throw error if spellcheck warnings exist
-      #   if: ${{ steps.spellcheck.outputs.num_warnings != 0 }}
-      #   run: 'echo "::error file=main.tex::num_warnings: ${{ steps.spellcheck.outputs.num_warnings }}"; exit 1;'
+      - name: Print number of spellcheck warnings
+        run: 'echo ${{ steps.spellcheck.outputs.num_warnings }}'
+
+      - name: Throw error if spellcheck warnings exist
+        if: ${{ steps.spellcheck.outputs.num_warnings > 409 }}
+        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.spellcheck.outputs.num_warnings }}"; exit 1;'
 
       - name: Compile LaTeX document
         uses: xu-cheng/latex-action@v2
